# Generated by Django 3.1.3 on 2020-12-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Locality', models.CharField(choices=[('VZ', 'VIZAG'), ('CI', 'CHENNAI'), ('VW', 'VIJAYAWADA'), ('NE', 'NELLORE'), ('SC', 'SRICITY')], default='VZ', max_length=20)),
                ('schoolname', models.CharField(choices=[('VZ', (('SCHOOL1', 'SC1'), ('SCHOOL2', 'SC2'), ('SCHOOL3', 'SC3'), ('SCHOOL4', 'SC4'), ('SCHOOL5', 'SC5'), ('SCHOOL6', 'SC6'))), ('CI', (('SCHOOL1', 'SC1'), ('SCHOOL2', 'SC2'), ('SCHOOL3', 'SC3'), ('SCHOOL4', 'SC4'), ('SCHOOL5', 'SC5'))), ('VW', (('SCHOOL1', 'SC1'), ('SCHOOL2', 'SC2'), ('SCHOOL3', 'SC3'), ('SCHOOL4', 'SC4'), ('SCHOOL5', 'SC5'))), ('NE', (('SCHOOL1', 'SC1'), ('SCHOOL2', 'SC2'), ('SCHOOL3', 'SC3'), ('SCHOOL4', 'SC4'), ('SCHOOL5', 'SC5'))), ('SC', (('SCHOOL1', 'SC1'), ('SCHOOL2', 'SC2'), ('SCHOOL3', 'SC3'), ('SCHOOL4', 'SC4'), ('SCHOOL5', 'SC5')))], max_length=200, verbose_name='schoolname')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('AC', 'ACADEMICS'), ('SP', 'SPORTS'), ('PL', 'PENALTY')], default='AC', max_length=20)),
                ('amount', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('youremail', models.EmailField(max_length=45)),
                ('phonenumber', models.CharField(max_length=30)),
                ('classandsection', models.CharField(max_length=30)),
                ('guardian_name', models.CharField(max_length=30, null=True)),
                ('Locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.locality')),
            ],
        ),
    ]
