# Generated by Django 3.1.3 on 2020-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('job_location', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='salary_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('job_location', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
