# Generated by Django 3.1.3 on 2020-12-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organisation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('notice_text', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=50)),
                ('enteredBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
