# Generated by Django 3.0.8 on 2020-11-12 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('school_name', models.CharField(blank=True, max_length=50, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='media/certificates')),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('school_name', models.CharField(blank=True, max_length=50, null=True)),
                ('standard', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
